{% set name = "dyntapy" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dyntapy-{{ version }}.tar.gz
  sha256: c55259ff08303a739f0b51bc35b1255dec70e30925e4f9e00ea005f710c0afbc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numba >=0.54.1
    - bokeh <3.0
    - osmnx
    - pandas
    - scipy
    - numpy
    - geojson
    - pyyaml
    - networkx
    - pyproj
    - geopandas
    - shapely
    - matplotlib-base
    - notebook
    - setuptools

test:
  imports:
    - dyntapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.kuleuven.be/ITSCreaLab/public-toolboxes/dyntapy
  summary: Macroscopic Static and Dynamic Traffic Assignment in Python
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - p-ortmann
